server:
  port: 8082
spring:
  application:
    name: comment-service
  # spring boot admin 配置
#  boot:
#    admin:
#      client:
#        url: http://${admin.host:127.0.0.1}:${admin.port:8070}

eureka:
  instance:
    # 续约间隔时间。每隔 30s 发送一次心跳。
    lease-renewal-interval-in-seconds: 5
    # 90s 内没有收到续约则注销实例。
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # 逗号后不能加空格。
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka # ,http://${eureka.host:127.0.0.1}:${eureka.port:8762}/eureka,http://${eureka.host:127.0.0.1}:${eureka.port:8763}/eureka