server:
  port: 8080

spring:
  application:
    name: user-service
  # spring boot admin 配置
#  boot:
#    admin:
#      client:
#        url: http://${admin.host:127.0.0.1}:${admin.port:8070}
  # druid 配置
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filter:
        stat:
          slow-sql-millis: 5000
          log-slow-sql: true
          merge-sql: true
      stat-view-servlet:
        url-pattern: /druid/*
      min-idle: 5
      max-active: 30
  # redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
  # mail 配置
  mail:
    username: 1390174365@qq.com
    host: smtp.qq.com
    password: oyemkayjalqwfica
    port: 587 #465
    test-connection: true

eureka:
  instance:
    # 续约间隔时间。每隔 30s 发送一次心跳。
    lease-renewal-interval-in-seconds: 5
    # 90s 内没有收到续约则注销实例。
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # 逗号后不能加空格。
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka # ,http://${eureka.host:127.0.0.1}:${eureka.port:8762}/eureka,http://${eureka.host:127.0.0.1}:${eureka.port:8763}/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
  type-aliases-package: com.jacksonfang.user.model

logging:
  level:
    # 打印 sql 语句。
    com.jacksonfang.user.mapper: debug

# customized properties
file:
  prefix: http://127.0.0.1:8888/images # Nginx 静态资源代理路径。